In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Shakshi\Desktop\HR project\IBM_HR_Attrition_Dataset.csv")

df.head()

,EmployeeNumber,Age,Gender,MaritalStatus,Education,Department,JobRole,JobLevel,BusinessTravel,OverTime,...,PerformanceRating,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance,TrainingTimesLastYear,SalarySlab,AgeBand,TenureBand,Attrition
0,1,47,Female,Married,1,Research & Development,Manager,2,Travel_Rarely,No,...,3,1,4,2,3,3,35K-60K,46+,0-3 yrs,No
1,2,43,Male,Married,2,Human Resources,Human Resources Representative,2,Non-Travel,No,...,4,4,3,3,3,2,<=35K,36-45,4-7 yrs,No
2,3,40,Female,Single,2,Research & Development,Research Scientist,1,Travel_Rarely,No,...,3,4,3,1,3,3,<=35K,36-45,0-3 yrs,Yes
3,4,46,Male,Single,4,Research & Development,Healthcare Representative,2,Travel_Rarely,No,...,3,4,4,3,3,2,<=35K,46+,4-7 yrs,No
4,5,36,Male,Single,2,Sales,Sales Representative,1,Travel_Rarely,No,...,3,2,4,2,1,4,<=35K,36-45,4-7 yrs,No

In [2]:
df.shape

(1470, 28)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeNumber            1470 non-null   int64
 1   Age                       1470 non-null   int64
 2   Gender                    1470 non-null   object
 3   MaritalStatus             1470 non-null   object
 4   Education                 1470 non-null   int64
 5   Department                1470 non-null   object
 6   JobRole                   1470 non-null   object
 7   JobLevel                  1470 non-null   int64
 8   BusinessTravel            1470 non-null   object
 9   OverTime                  1470 non-null   object
 10  MonthlyIncome             1470 non-null   int64
 11  PercentSalaryHike         1470 non-null   float64
 12  StockOptionLevel          1470 non-null   int64
 13  TotalWorkingYears         1470 non-null   int64
 14  YearsAtCompany            1470 non-null   int64
 15  YearsInCurrentRole        1470 non-null   int64
 16  YearsWithCurrManager      1470 non-null   int64
 17  YearsSinceLastPromotion   1470 non-null   int64
 18  PerformanceRating         1470 non-null   int64
 19  JobSatisfaction           1470 non-null   int64
 20  EnvironmentSatisfaction   1470 non-null   int64
 21  RelationshipSatisfaction  1470 non-null   int64
 22  WorkLifeBalance           1470 non-null   int64
 23  TrainingTimesLastYear     1470 non-null   int64
 24  SalarySlab                1470 non-null   object
 25  AgeBand                   1470 non-null   object
 26  TenureBand                1470 non-null   object
 27  Attrition                 1470 non-null   object
dtypes: float64(1), int64(17), object(10)
memory usage: 321.7+ KB

In [4]:
df['Attrition'].value_counts()

Attrition
No     1169
Yes     301
Name: count, dtype: int64

In [5]:
round(df['Attrition'].value_counts(normalize=True)*100,2)

Attrition
No     79.52
Yes    20.48
Name: proportion, dtype: float64

In [6]:
round(
    pd.crosstab(
        df['Department'],
        df['Attrition'],
        normalize='index'
    ) * 100,
    2
)

Attrition                  No    Yes
Department
Human Resources         73.19  26.81
Research & Development  81.17  18.83
Sales                   78.31  21.69

In [7]:
round(
    pd.crosstab(
        df['SalarySlab'],
        df['Attrition'],
        normalize='index'
    ) * 100,
    2
)

Attrition      No    Yes
SalarySlab
35K-60K     87.60  12.40
<=35K       72.74  27.26
>60K        90.78   9.22

In [8]:
round(
    pd.crosstab(
        df['AgeBand'],
        df['Attrition'],
        normalize='index'
    ) * 100,
    2
)

Attrition     No    Yes
AgeBand
18-25      74.85  25.15
26-35      79.37  20.63
36-45      80.57  19.43
46+        80.69  19.31

In [9]:
round(
    pd.crosstab(
        df['TenureBand'],
        df['Attrition'],
        normalize='index'
    ) * 100,
    2
)

Attrition      No    Yes
TenureBand
0-3 yrs     77.66  22.34
4-7 yrs     79.67  20.33
8+ yrs      83.90  16.10

In [10]:
risk = df[
    (df['JobRole'] == 'Sales Executive') &
    (df['TenureBand'] == '0-3 yrs') &
    (df['SalarySlab'] == '<=35K')
]

round(risk['Attrition'].value_counts(normalize=True) * 100, 2)

Attrition
No     68.89
Yes    31.11
Name: proportion, dtype: float64

In [11]:
leavers = df[df['Attrition'] == 'Yes']

round(
    (leavers['YearsSinceLastPromotion'] >= 5).mean() * 100,
    2
)

np.float64(11.3)